[package]
name = "memorymap-compiler-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
memorymap-compiler-base = { path = "../memorymap-compiler-base" }
heck = "0.5.0"
quote = "1.0"
proc-macro2 = "1.0"
